### ISSUE TITLE
Allow ServerHandler to return futures

### ISSUE THREAD

**Issue by jadamcrain** [stepfunc/rodbus#10]
In case requests take some time, e.g. database calls.

**Comment by jadamcrain** [comment]
This isn't really possible ATM b/c you can't have `impl Future` return type on trait methods. If you're not using the trait dynamically, I don't see why this shouldn't be possible in the future since the compiler would know the exact size of the `impl Future`. We'll keep this here as a placeholder.

**Comment by emgre** [comment]
Perhaps reuse the `MaybeAsync` type from DNP3.

**Comment by jadamcrain** [comment]
Making these methods `async` has the additional complication that you can no longer use `std::sync::Mutex` to protect the handler, b/c the guard cannot be held across an await point.
