### ISSUE TITLE
Add custom function code like tokio-modbus

### ISSUE THREAD

**Issue by takkuumi** [stepfunc/rodbus#114]
Add custom function code like tokio-modbus [Custom](https://docs.rs/tokio-modbus/latest/tokio_modbus/prelude/enum.Request.html#variant.Custom)

**Comment by jadamcrain** [comment]
If a customer requests this feature, we'll add it. Given the commercial nature of this library we don't really take feature requests in issue tracker. If you like to have this added as part of a license sale send an email to `info@stepfunc.io`.
