### ISSUE TITLE
cbindgen not exporting rodbus public constants

### ISSUE THREAD

**Issue by jadamcrain** [stepfunc/rodbus#17]
Really want to have the count limits and the exception code constants in rodbus.h/rodbus.hpp

**Comment by jadamcrain** [comment]
I have raised an issue [here](https://github.com/eqrion/cbindgen/issues/445) to see how to proceed

**Comment by jadamcrain** [comment]
I defined the required constants directly in the FFI module. Not ideal in terms of duplication, but I will now remove the milestone tag so it doesn't block the release.

**Comment by emgre** [comment]
The trick is the following:
```toml
[parse]
parse_deps = true
include = ["rodbus", "tokio"]
extra_bindings = ["rodbus"]
```

The `parse_deps` says to also read from dependent crates for stuff to export. It only exports what we use in `rodbus-ffi`, so you get the `Channel` (from `rodbus`) and the `Runtime` (from `tokio`). The `include` whitelists what we want to look at.

The `extra_bindings` exports all the public constants and public functions from the dependent crates listed. If we want to export the constants, we need this. However, it's all or nothing AFAIK.

**Comment by jadamcrain** [comment]
Nice find. It'd be nice if `cbindgen` could not only whitelist crates, but modules within crates... I guess I'm happy enough with duplicating the few constants in the FFI crate.  I'll go update the ticket on the cbindgen project.

**Comment by emgre** [comment]
We don't use cbindgen anymore.
