### ISSUE TITLE
Feature Request: Rodbus-client: Show TX/RX bytes and output hex

### ISSUE THREAD

**Issue by cutaway** [stepfunc/rodbus#38]
There are two features that are very useful in `mbtget`. The first is the ability to output the values in hex (rather than decimal) and the second is to display the TX and RX bytes. The following is an example that shows both.

`
CutSec 2020-09-17 07:38:03
> ./mbtget -d -hex -a 0 -n 5
Tx
[84 C6 00 00 00 06 01] 03 00 00 00 05

Rx
[84 C6 00 00 00 0D 01] 03 0A 00 00 00 1E 00 00 00 00 00 3C

values:
  1 (ad 00000): 0x0000
  2 (ad 00001): 0x001e
  3 (ad 00002): 0x0000
  4 (ad 00003): 0x0000
  5 (ad 00004): 0x003c
`

I'm reviewing the code to see if I can implement it, but I'm new to Rust (just installed) and it might take a while for me to do it. Plus, I doubt I would do it in the most effective manner.

Thank you,
cutaway

**Comment by jadamcrain** [comment]
cool, we can definitely emulate these features.

**Comment by emgre** [comment]
The new logging interface introduced in #44 allows logging at the physical layer, PDU and ADU level, all configurable.
